twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        pumukit2_info: "%pumukit2.info%"
        locales:       "%pumukit2.locales%"
