version: '3.4'

services:
  php:
    image: teltek/pumukit:$PUMUKIT_BASE_VERSION
    env_file:
      - .env
    build:
      context: ./
      args: 
        - PUMUKIT_BASE_VERSION=$PUMUKIT_BASE_VERSION
      cache_from:
        - teltek/pumukit
        - teltek/nginx
    depends_on:
      - db
    # Comment out the next line for dev
    # volumes:
      #- ./:/srv/pumukit
    # Comment out the next lines in production
    # volumes:
      # - ./web/storage:/srv/pumukit/web/storage:rw,cached
      # - ./web/uploads:/srv/pumukit/web/uploads:rw,cached
      # - ./web/bundles:/srv/pumukit/web/bundles:rw,cached

  h2-proxy:
    image: teltek/nginx:$PUMUKIT_BASE_VERSION
    env_file:
      - .env
    build:
      context: ./doc/docker/nginx
      cache_from:
        - teltek/pumukit
        - teltek/nginx
    depends_on:
      - php
    # Comment out the next line for dev
    # volumes:
      #- ./:/srv/pumukit
    # Comment out the next lines in production
    # volumes:
      # - ./web/storage:/srv/pumukit/web/storage:rw,cached
      # - ./web/uploads:/srv/pumukit/web/uploads:rw,cached
      # - ./web/bundles:/srv/pumukit/web/bundles:rw,cached
      
    ports:
      - "80:80"
      - "443:443"

  db:
    image: mongo:4.0
    volumes:
      - db-data:/data/db:rw

volumes:
  db-data: {}
