# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  env(MONGODB_URL): 'mongodb://localhost:27017'
  env(MONGODB_DB): 'pumukit'
  locale:  "%env(PUMUKIT_LOCALE)%"
  secret:  "%env(PUMUKIT_SECRET)%"

  debug_toolbar:          true
  debug_redirects:        false
  use_assetic_controller: true

  pumukit.info:
    title:               "%env(PUMUKIT_TITLE)%"
    description:         "%env(PUMUKIT_DESCRIPTION)%"
    keywords:            "%env(PUMUKIT_KEYWORDS)%"
    email:               "%env(PUMUKIT_EMAIL)%"
    logo:                "%env(PUMUKIT_LOGO)%"
    primary_color:       "%env(PUMUKIT_PRIMARY_COLOR)%"
    font_color:          "%env(PUMUKIT_FONT_COLOR)%"
  pumukit.locales:
    - "%env(PUMUKIT_DEFAULT_LOCALE_1)%"
    - "%env(PUMUKIT_DEFAULT_LOCALE_2)%"
  pumukit.uploads_dir:     "%env(PUMUKIT_UPLOADS_DIR)%"
  pumukit.uploads_url:     "%env(PUMUKIT_UPLOADS_URL)%"
  pumukit.inbox:           "%env(PUMUKIT_INBOX)%"
  pumukit.tmp:             "%env(PUMUKIT_TMP)%"
  pumukit.delete_on_disk:  "%env(bool:PUMUKIT_DELETE_ON_DISK)%"

  pumukit.naked_backoffice_domain: 'localhost-naked'
  pumukit.naked_backoffice_background: ''
  pumukit.naked_backoffice_color: ''
  pumukit.naked_custom_css_url: ''

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true       # Allows optimizing the container by removing unused services; this also means

  App\:
    resource: '../src/*'
    exclude: '../src/{Pumukit,Entity,Migrations,Tests,Kernel.php}'

#  App\Controller\:
#    resource: '../src/Controller'
#    tags: ['controller.service_arguments']

  Pumukit\:
    resource: '../src/Pumukit/'
    exclude: '../src/Pumukit/*/{Repository,Document,Event,Security,EventListener,Utils}'

  Pumukit\BaseLivePlayerBundle\Twig\LiveTwigExtension:
    arguments:
      - "@doctrine_mongodb.odm.document_manager"
      - "@pumukit_live.live"
      - "@pumukitschema.eventsession"
      - "%pumukit_new_admin.advance_live_event_create_default_pic%"

  Pumukit\BasePlayerBundle\Services\IntroService:
    arguments:
      - '%pumukit.intro%'

  Pumukit\BasePlayerBundle\Services\TrackUrlService:
    arguments:
      - "@doctrine_mongodb.odm.document_manager"
      - "@router"
      - "%pumukitplayer.secure_secret%"
      - "%pumukitplayer.secure_duration%"

  Pumukit\CoreBundle\Services\FilterService:
    arguments:
      - '@doctrine_mongodb.odm.document_manager'
      - '@pumukitschema.person'
      - '@security.csrf.token_storage'
      - '%pumukitschema.enable_add_user_as_person%'

  Pumukit\CoreBundle\Services\TwigTemplateLoaderService:
    arguments:
      - '@file_locator'
      - '@templating.name_parser'
      - ''
      - ''
      - ''

  Pumukit\EncoderBundle\Services\CpuService:
    arguments:
      - '%pumukitencode.cpulist%'
      - '@doctrine_mongodb.odm.document_manager'

  Pumukit\EncoderBundle\Services\DynamicPicExtractorService:
    arguments:
      - '@doctrine_mongodb.odm.document_manager'
      - '@pumukitschema.mmspic'
      - '%pumukit.uploads_dir%/pic'
      - '%pumukit.uploads_url%/pic'
      - '%pumukit.dynamicpicextractor.command%'

  Pumukit\EncoderBundle\Services\JobService:
    arguments:
      - '@doctrine_mongodb.odm.document_manager'
      - '@pumukitencoder.profile'
      - '@pumukitencoder.cpu'
      - '@pumukit.inspection'
      - '@event_dispatcher'
      - '@logger'
      - '@pumukitschema.track'
      - '@security.csrf.token_storage'
      - '@pumukitencoder.mmpropertyjob'
      - '%kernel.root_dir%/../bin/'
      - '%kernel.environment%'
      - '%pumukit.tmp%'
      - '%pumukit.inbox%'
      - '%pumukitencode.delete_inbox_files%'

  Pumukit\EncoderBundle\Services\PicExtractorService:
    arguments:
      $width: '%pumukitencode.thumbnail.width%'
      $height: '%pumukitencode.thumbnail.height%'
      $targetPath: '%pumukit.uploads_dir%/pic'
      $targetUrl: '%pumukit.uploads_url%/pic'
      $command: '%pumukit.picextractor.command%'

  Pumukit\EncoderBundle\Services\ProfileService:
    arguments:
      - '%pumukitencode.profilelist%'
      - '@doctrine_mongodb.odm.document_manager'
      - '%pumukitencode.target_default_profiles%'

  Pumukit\NewAdminBundle\EventListener\NakedBackofficeListener:
    arguments:
        $domain: '%pumukit.naked_backoffice_domain%'
        $background: '%pumukit.naked_backoffice_background%'
        $color: '%pumukit.naked_backoffice_color%'
        $customCssURL: '%pumukit.naked_custom_css_url%'

  Pumukit\NewAdminBundle\Services\TagCatalogueService:
    arguments:
      - '@doctrine_mongodb.odm.document_manager'
      - '@translator'
      - '@router'
      - '%pumukit_new_admin.base_catalogue_tag%'
      - '%pumukit.locales%'

  Pumukit\NotificationBundle\Services\JobNotificationService:
    arguments:
      $enable: false
      $environment: ''
      $template: ''
      $subjectSuccess: ''
      $subjectFails: ''
      $subjectSuccessTrans: ''
      $subjectFailsTrans: ''

  Pumukit\NotificationBundle\Services\SenderService:
    arguments:
      $mailer: ''
      $enable: ''
      $senderEmail: ''
      $senderName: ''
      $enableMultiLang: ''
      $locales: ''
      $subjectSuccessTrans: ''
      $subjectFailsTrans: ''
      $adminEmail: ''
      $notificateErrorsToAdmin: ''
      $platformName: ''
      $environment: ''

  Pumukit\SchemaBundle\Security\RoleHierarchy:
    arguments:
      $hierarchy: ''

  Pumukit\SchemaBundle\Services\EmbeddedEventSessionService:
    arguments:
      - '@doctrine_mongodb.odm.document_manager'
      - '%pumukitschema.event_default_poster%'
      - '%pumukit_new_admin.advance_live_event_create_default_pic%'

  Pumukit\SchemaBundle\Services\LegacyEventPicService:
    arguments:
      $targetPath: '%pumukit.uploads_dir%/pic'
      $targetUrl: '%pumukit.uploads_url%/pic'
      $forceDeleteOnDisk: '%pumukit.delete_on_disk%'

  Pumukit\SchemaBundle\Services\MaterialService:
    arguments:
      $targetPath: '%pumukit.uploads_dir%/pic'
      $targetUrl: '%pumukit.uploads_url%/pic'
      $forceDeleteOnDisk: '%pumukit.delete_on_disk%'

  Pumukit\SchemaBundle\Services\MultimediaObjectPicService:
    arguments:
      $targetPath: '%pumukit.uploads_dir%/pic'
      $targetUrl: '%pumukit.uploads_url%/pic'
      $forceDeleteOnDisk: '%pumukit.delete_on_disk%'

  Pumukit\SchemaBundle\Services\SeriesPicService:
    arguments:
      $locales: '%pumukit.locales%'
      $targetPath: '%pumukit.uploads_dir%/pic'
      $targetUrl: '%pumukit.uploads_url%/pic'
      $forceDeleteOnDisk: '%pumukit.delete_on_disk%'

  Pumukit\WebTVBundle\Services\BreadcrumbsService:
    alias: pumukit_web_tv.breadcrumbs

  Pumukit\WebTVBundle\Services\CategoriesService:
    arguments:
      $parentCod: '%categories_tag_cod%'
      $listGeneralParam: '%categories.list_general_tags%'

  Pumukit\WebTVBundle\Services\LinkService:
    arguments:
      $linkTagToSearch: '%pumukit_web_tv.linktagtosearch%'

  Pumukit\WebTVBundle\Services\ListService:
    arguments:
      $advanceLiveEvents: '%pumukit_new_admin.advance_live_event%'
      $wallTag: '%wall_block.wall_tag%'

  Pumukit\WebTVBundle\Services\MenuService:
    arguments:
      $advanceEvents: '%pumukit_new_admin.advance_live_event%'

  Pumukit\WebTVBundle\Services\SearchService:
    arguments:
      $parentTagCod: '%search.parent_tag.cod%'
      $parentTagCodOptional: '%search.parent_tag_2.cod%'

  Pumukit\WebTVBundle\Twig\PumukitExtension:
    arguments:
      - '@doctrine_mongodb.odm.document_manager'
      - '@router.request_context'
      - '%pumukit_web_tv.default_pic%'
      - '@pumukitschema.caption'
      - '@pumukitschema.pic'
      - '@pumukit_web_tv.link_service'
      - '@pumukitschema.mmsduration'

  Pumukit\WizardBundle\DependencyInjection\Configuration:
    arguments:
      $profiles: ''

  Pumukit\WizardBundle\Services\LicenseService:
    arguments:
      $showLicense: '%pumukit_wizard.show_license%'
      $licenseDir: '%pumukit_wizard.license_dir%'
      $locales: '%pumukit.locales%'

  Pumukit\WizardBundle\Services\WizardService:
    arguments:
      $basePath: '%kernel.root_dir%/../'
      $locales: '%pumukit.locales%'
      $inboxDepth: '%pumukit.inbox_depth%'



#  App\Command\InitializeCommand:
#    arguments:
#      - "@kernel"
#      - "@doctrine_mongodb.odm.document_manager"
#      - "@pumukitschema.permission"
#      - "%pumukit.locales%"
#    tags:
#      - { name: 'console.command', command: 'pumukit:initialize' }


  Pumukit\WebTVBundle\Controller\IndexController:
    arguments:
      $showStats: '%menu.show_stats%'
