pumukitnewadmin_eventpic_create:
    path: /create/{id}
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LegacyEventPicController::createAction

pumukitnewadmin_eventpic_update:
    path: /{id}/update
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LegacyEventPicController::updateAction

pumukitnewadmin_eventpic_upload:
    path: /{id}/upload
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LegacyEventPicController::uploadAction

pumukitnewadmin_eventpic_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LegacyEventPicController::deleteAction
