pumukitnewadmin_event_index:
    path: /
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LegacyEventController::indexAction
        _sylius:
            filterable: true

pumukitnewadmin_event_create:
    path: /create
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LegacyEventController::createAction
        _sylius:
            redirect: pumukitnewadmin_event_index

pumukitnewadmin_event_update:
    path: /{id}/update
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LegacyEventController::updateAction
        _sylius:
            redirect: pumukitnewadmin_event_index

pumukitnewadmin_event_batch_delete:
    path: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LegacyEventController::batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_event_index

pumukitnewadmin_event_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LegacyEventController::deleteAction
        _sylius:
            redirect: pumukitnewadmin_event_index

pumukitnewadmin_event_show:
    path: /{id}/show
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LegacyEventController::showAction

pumukitnewadmin_event_list:
    path: /list
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LegacyEventController::listAction
        _sylius:
            filterable: true

pumukitnewadmin_event_updatesession:
    path: /updatesession
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LegacyEventController::updateSessionAction
