pumukitnewadmin_live_index:
    path: /
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LiveController::indexAction
        _sylius:
            filterable: true

pumukitnewadmin_live_create:
    path: /create
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LiveController::createAction
        _sylius:
            redirect: pumukitnewadmin_live_index

pumukitnewadmin_live_update:
    path: /{id}/update
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LiveController::updateAction
        _sylius:
            redirect: pumukitnewadmin_live_index

pumukitnewadmin_live_batch_delete:
    path: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LiveController::batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_live_index

pumukitnewadmin_live_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LiveController::deleteAction
        _sylius:
            redirect: pumukitnewadmin_live_index

pumukitnewadmin_live_copy:
    path: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LiveController::copyAction
        _sylius:
            redirect: pumukitnewadmin_live_index

pumukitnewadmin_live_show:
    path: /{id}/show
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LiveController::showAction

pumukitnewadmin_live_list:
    path: /list
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\LiveController::listAction
        _sylius:
            filterable: true
