pumukitnewadmin_mmspic_index:
    path: /
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectPicController::indexAction
        _sylius:
            filterable: true

pumukitnewadmin_mmspic_create:
    path: /create/{id}
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectPicController::createAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mmspic_generate:
    path: /generate/{id}
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectPicController::generateAction

pumukitnewadmin_mmspic_update:
    path: /{id}/update
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectPicController::updateAction

pumukitnewadmin_mmspic_batch_delete:
    path: /batch_delete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectPicController::batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_mms_index

pumukitnewadmin_mmspic_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectPicController::deleteAction


pumukitnewadmin_mmspic_up:
    path: /{id}/up
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectPicController::upAction


pumukitnewadmin_mmspic_down:
    path: /{id}/down
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectPicController::downAction


pumukitnewadmin_mmspic_list:
    path: /{id}/list
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectPicController::listAction


pumukitnewadmin_mmspic_show:
    path: /{id}/show
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectPicController::showAction


pumukitnewadmin_mmspic_upload:
    path: /{id}/upload
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectPicController::uploadAction

pumukitnewadmin_mmspic_picstoaddlist:
    path: /{id}/picstoaddlist
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\MultimediaObjectPicController::picstoaddlistAction
