pumukitnewadmin_permissionprofile_index:
    path: /
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PermissionProfileController::indexAction
        _sylius:
            filterable: true

pumukitnewadmin_permissionprofile_create:
    path: /create
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PermissionProfileController::createAction
        _sylius:
            redirect: pumukitnewadmin_permissionprofile_index

pumukitnewadmin_permissionprofile_update:
    path: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PermissionProfileController::updateAction
        _sylius:
            redirect: pumukitnewadmin_permissionprofile_index

pumukitnewadmin_permissionprofile_batch_delete:
    path: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PermissionProfileController::batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_permissionprofile_index

pumukitnewadmin_permissionprofile_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PermissionProfileController::deleteAction
        _sylius:
            redirect: pumukitnewadmin_permissionprofile_index

pumukitnewadmin_permissionprofile_list:
    path: /list
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PermissionProfileController::listAction

pumukitnewadmin_permissionprofile_batch_update:
    path: /batchupdate
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PermissionProfileController::batchUpdateAction
        _sylius:
            redirect: pumukitnewadmin_permissionprofile_index

pumukitnewadmin_permissionprofile_export:
    path: /export
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PermissionProfileController::exportPermissionProfilesAction
