pumukitnewadmin_playlistmms_index:
    path: /
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::indexAction
        filter: false
        _sylius:
            filterable: true

pumukitnewadmin_playlistmms_create:
    path: /{id}/create
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::createAction
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_show:
    path: /{id}/show
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::showAction
        filter: false

pumukitnewadmin_playlistmms_info:
    path: /{id}/info
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::infoAction
        filter: false

pumukitnewadmin_playlistmms_up:
    path: /{id}/up
    methods: [GET, PUT, POST]
    defaults:
        filter: false
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::upAction
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_down:
    path: /{id}/down
    methods: [GET, PUT, POST]
    defaults:
        filter: false
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::downAction
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_top:
    path: /{id}/top
    methods: [GET, PUT, POST]
    defaults:
        filter: false
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::topAction
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_bottom:
    path: /{id}/bottom
    methods: [GET, PUT, POST]
    defaults:
        filter: false
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::bottomAction
        _sylius:
            redirect: pumukitnewadmin_playlistmms_index

pumukitnewadmin_playlistmms_list:
    path: /list
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::listAction
        filter: false

pumukitnewadmin_playlistmms_cut:
    path: /cut
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::cutAction

pumukitnewadmin_playlistmms_paste:
    path: /paste
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::pasteAction

pumukitnewadmin_playlistmms_reorder:
    path: /reorder
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::reorderAction

pumukitnewadmin_playlistmms_modal:
    path: /{id}/modal
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::modalAction

pumukitnewadmin_playlistmms_modal_mymmobjs:
    path: /{id}/modal_mymmobjs
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::modalMyMmobjsAction

pumukitnewadmin_playlistmms_modal_search:
    path: /modal_search
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::searchModalAction

pumukitnewadmin_playlistmms_modal_url:
    path: /modal_url
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::urlModalAction

pumukitnewadmin_playlistmms_batch_add:
    path: /{id}/add
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::addBatchAction

pumukitnewadmin_playlistmms_batch_delete:
    path: /{id}/delete
    methods: [GET, POST, DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::deleteBatchAction

pumukitnewadmin_playlistmms_modal_add:
    path: /modal
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::addModalAction

pumukitnewadmin_playlistmms_batch_add_to_several_playlist:
    path: /
    methods: [POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::addBatchToSeveralPlaylistAction

pumukitnewadmin_playlistmms_links:
    path: /{id}/links
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\PlaylistMultimediaObjectController::infoAction
