pumukitnewadmin_role_index:
    path: /
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\RoleController::indexAction
        _sylius:
            filterable: true
            sorting:
                rank: desc

pumukitnewadmin_role_create:
    path: /create
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\RoleController::createAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_update:
    path: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\RoleController::updateAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_batch_delete:
    path: /delete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\RoleController::batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_delete:
    path: /{id}
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\RoleController::deleteAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_copy:
    path: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\RoleController::copyAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_up:
    path: /{id}/up
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\RoleController::upAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_down:
    path: /{id}/down
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\RoleController::downAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_top:
    path: /{id}/top
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\RoleController::topAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_bottom:
    path: /{id}/bottom
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\RoleController::bottomAction
        _sylius:
            redirect: pumukitnewadmin_role_index

pumukitnewadmin_role_list:
    path: /list
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\RoleController::listAction

pumukitnewadmin_role_export:
    path: /export
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\RoleController::exportRolesAction
