pumukitnewadmin_seriestype_index:
    path: /
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\SeriesTypeController::indexAction
        _sylius:
            filterable: true

pumukitnewadmin_seriestype_create:
    path: /create
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\SeriesTypeController::createAction
        _sylius:
            redirect: pumukitnewadmin_seriestype_index

pumukitnewadmin_seriestype_update:
    path: /{id}/update
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\SeriesTypeController::updateAction
        _sylius:
            redirect: pumukitnewadmin_seriestype_index

pumukitnewadmin_seriestype_batch_delete:
    path: /batchdelete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\SeriesTypeController::batchDeleteAction
        _sylius:
            redirect: pumukitnewadmin_seriestype_index

pumukitnewadmin_seriestype_delete:
    path: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\SeriesTypeController::deleteAction
        _sylius:
            redirect: pumukitnewadmin_seriestype_index

pumukitnewadmin_seriestype_copy:
    path: /{id}/copy
    methods: [GET, PUT, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\SeriesTypeController::copyAction
        _sylius:
            redirect: pumukitnewadmin_seriestype_index

pumukitnewadmin_seriestype_show:
    path: /{id}/show
    methods: [GET]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\SeriesTypeController::showAction

pumukitnewadmin_seriestype_list:
    path: /list
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\NewAdminBundle\Controller\SeriesTypeController::listAction
        _sylius:
            filterable: true
