pumukitwizard_default_index:
    path: /
    methods: [GET]
    defaults:
        _controller: Pumukit\WizardBundle\Controller\DefaultController::seriesAction

pumukitwizard_default_license:
    path: /license
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\WizardBundle\Controller\DefaultController::licenseAction

pumukitwizard_default_series:
    path: /series
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\WizardBundle\Controller\DefaultController::seriesAction

pumukitwizard_default_type:
    path: /type/{id}
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\WizardBundle\Controller\DefaultController::typeAction

pumukitwizard_default_option:
    path: /option
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\WizardBundle\Controller\DefaultController::optionAction

pumukitwizard_default_multimediaobject:
    path: /multimediaobject
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\WizardBundle\Controller\DefaultController::multimediaobjectAction

pumukitwizard_default_track:
    path: /track
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\WizardBundle\Controller\DefaultController::trackAction

pumukitwizard_default_upload:
    path: /upload
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\WizardBundle\Controller\DefaultController::uploadAction

pumukitwizard_default_end:
    path: /end
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\WizardBundle\Controller\DefaultController::endAction

pumukitwizard_default_error:
    path: /error
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\WizardBundle\Controller\DefaultController::errorAction
