pumukitwizard_simple_index:
    path: /index/{id}
    methods: [GET]
    defaults:
        _controller: Pumukit\WizardBundle\Controller\DefaultController::indexAction

pumukitwizard_simple_upload:
    path: /upload/{id}
    methods: [POST]
    defaults:
        _controller: Pumukit\WizardBundle\Controller\DefaultController::uploadAction

pumukitwizard_simple_embedindex:
    path: /embedindex
    methods: [GET]
    defaults:
        _controller: Pumukit\WizardBundle\Controller\DefaultController::embedindexAction

pumukitwizard_simple_embedupload:
    path: /embedupload
    methods: [GET, POST]
    defaults:
        _controller: Pumukit\WizardBundle\Controller\DefaultController::embeduploadAction
